# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: test.proto for package 'grpc.sample'

require 'grpc'
require 'test_pb'

module Grpc
  module Sample
    module SampleService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'grpc.sample.SampleService'

        rpc :SampleCall, ::Grpc::Sample::SampleRequest, ::Grpc::Sample::SampleResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
